-- MySQL Script generated by MySQL Workbench
-- Ср 21 дек 2016 18:30:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_naushniki
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_naushniki` ;

-- -----------------------------------------------------
-- Schema db_naushniki
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_naushniki` DEFAULT CHARACTER SET utf8 ;
USE `db_naushniki` ;

-- -----------------------------------------------------
-- Table `db_naushniki`.`pages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_naushniki`.`pages` ;

CREATE TABLE IF NOT EXISTS `db_naushniki`.`pages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent` INT NOT NULL,
  `level` INT NOT NULL,
  `sort` DOUBLE NOT NULL,
  `title` VARCHAR(500) NOT NULL,
  `description` VARCHAR(2000) NULL,
  `url` VARCHAR(2048) NOT NULL,
  `flags` BIT(4) NOT NULL DEFAULT b'0001' COMMENT 'Первый бит: показывать / не показывать пункт меню.\nВторой бит: перенос строки в меню с этого пункта.\nОстальные про запас.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `sort_UNIQUE` (`sort` ASC),
  INDEX `parent` (`parent` ASC),
  CONSTRAINT `fk_parent`
    FOREIGN KEY (`parent`)
    REFERENCES `db_naushniki`.`pages` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_naushniki`.`points`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_naushniki`.`points` ;

CREATE TABLE IF NOT EXISTS `db_naushniki`.`points` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_naushniki`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_naushniki`.`orders` ;

CREATE TABLE IF NOT EXISTS `db_naushniki`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fio` VARCHAR(200) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(254) NOT NULL,
  `comment` VARCHAR(2000) NULL,
  `advanced` VARCHAR(2000) NULL,
  `vadis` VARCHAR(200) NULL,
  `rerum` TINYINT(1) NULL,
  `delivery` VARCHAR(45) NOT NULL,
  `points_id` INT NULL,
  `street` VARCHAR(200) NULL,
  `house` VARCHAR(45) NULL,
  `entrance` VARCHAR(45) NULL,
  `intercom` VARCHAR(45) NULL,
  `floor` VARCHAR(45) NULL,
  `flat` VARCHAR(45) NULL,
  `building` VARCHAR(45) NULL,
  `latin` VARCHAR(2000) NULL,
  INDEX `fk_orders_points_id_idx` (`points_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_orders_points_id`
    FOREIGN KEY (`points_id`)
    REFERENCES `db_naushniki`.`points` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_naushniki`.`pages`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_naushniki`;
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (0, DEFAULT, 0, 0, 'Корень', NULL, '/', b'0000');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (1, 0, 1, 1, 'Блютуз наушники', 'Краткое описание раздела, показывающееся при наведении мыши на ссылку в меню.', '/bluetoothheadphones', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (2, 0, 1, 2, 'Микронаушники', NULL, '/microheadphones', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (3, 0, 1, 3, 'Блютуз колонки', NULL, '/bluetoothspeakers', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (4, 0, 1, 4, 'Аксессуары', NULL, '/accessories', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (5, 0, 1, 5, 'Доставка и Оплата', NULL, '/deliverypayment', b'0011');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (6, 5, 2, 6, 'Lorem', NULL, '/deliverypayment/lorem', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (7, 5, 2, 7, 'Ipsum', NULL, '/deliverypayment/ipsum', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (8, 5, 2, 8, 'Et cetera terra terra', NULL, '/deliverypayment/etceteraterraterra', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (9, 8, 3, 9, 'Lorem', NULL, '/deliverypayment/etceteraterraterra/lorem', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (10, 8, 3, 10, 'Ipsum', NULL, '/deliverypayment/etceteraterraterra/ipsum', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (11, 0, 1, 11, 'Гарантия', NULL, '/guarantee', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (12, 0, 1, 12, 'О нас', NULL, '/about', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (13, 0, 1, 13, 'Контакты', NULL, '/contacts', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (14, 2, 2, 2.5, 'Пункт меню', NULL, '/microheadphones/item1', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (15, 2, 2, 2.75, 'Пункт меню с подразделами', NULL, '/microheadphones/item2', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (16, 15, 3, 2.875, 'Подпункт меню', '', '/microheadphones/item2/item1', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (17, 15, 3, 2.9375, 'Подпункт меню с подразделами', '', '/microheadphones/item2/item2', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (18, 17, 4, 2.96875, 'Подраздел подраздела', '', '/microheadphones/item2/item2/item1', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (19, 17, 4, 2.984375, 'И так далее', NULL, '/microheadphones/item2/item2/item2', b'0001');
INSERT INTO `db_naushniki`.`pages` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (20, 2, 2, 2.9921875, 'Ещё пункт меню', NULL, '/microheadphones/item3', b'0001');

COMMIT;


-- -----------------------------------------------------
-- Data for table `db_naushniki`.`points`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_naushniki`;
INSERT INTO `db_naushniki`.`points` (`id`, `title`) VALUES (1, 'Деревня дедушки');
INSERT INTO `db_naushniki`.`points` (`id`, `title`) VALUES (2, 'Та водонапорная башня, ну, ты помнишь…');
INSERT INTO `db_naushniki`.`points` (`id`, `title`) VALUES (3, 'г. Москва, Старонововыхухолевый пер., 37');

COMMIT;

