-- MySQL Script generated by MySQL Workbench
-- Ср 21 дек 2016 18:42:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_shop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_shop` ;

-- -----------------------------------------------------
-- Schema db_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_shop` DEFAULT CHARACTER SET utf8 ;
USE `db_shop` ;

-- -----------------------------------------------------
-- Table `db_shop`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_shop`.`categories` ;

CREATE TABLE IF NOT EXISTS `db_shop`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent` INT NOT NULL,
  `level` INT NOT NULL,
  `sort` DOUBLE NOT NULL,
  `title` VARCHAR(500) NOT NULL,
  `description` VARCHAR(2000) NULL,
  `url` VARCHAR(2048) NOT NULL,
  `flags` BIT(4) NOT NULL DEFAULT b'0001' COMMENT 'Первый бит: показывать / не показывать пункт меню.\nВторой бит: перенос строки в меню с этого пункта.\nОстальные про запас.\n',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `sort_UNIQUE` (`sort` ASC),
  INDEX `parent` (`parent` ASC),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  CONSTRAINT `fk_categories_parent_id`
    FOREIGN KEY (`parent`)
    REFERENCES `db_shop`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shop`.`goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_shop`.`goods` ;

CREATE TABLE IF NOT EXISTS `db_shop`.`goods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `article` VARCHAR(45) NOT NULL,
  `title` VARCHAR(500) NOT NULL,
  `description` VARCHAR(50000) NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `instock` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `article_UNIQUE` (`article` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shop`.`categories_has_goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_shop`.`categories_has_goods` ;

CREATE TABLE IF NOT EXISTS `db_shop`.`categories_has_goods` (
  `categories_id` INT NOT NULL,
  `goods_id` INT NOT NULL,
  `sort` DOUBLE NOT NULL,
  PRIMARY KEY (`categories_id`, `goods_id`),
  INDEX `fk_categories_has_goods_goods1_idx` (`goods_id` ASC),
  INDEX `fk_categories_has_goods_categories1_idx` (`categories_id` ASC),
  UNIQUE INDEX `sort_UNIQUE` (`sort` ASC),
  CONSTRAINT `fk_categories_has_goods_categories_id`
    FOREIGN KEY (`categories_id`)
    REFERENCES `db_shop`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_categories_has_goods_goods_id`
    FOREIGN KEY (`goods_id`)
    REFERENCES `db_shop`.`goods` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shop`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_shop`.`users` ;

CREATE TABLE IF NOT EXISTS `db_shop`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `secondname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `address` VARCHAR(500) NOT NULL,
  `passwordhash` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shop`.`delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_shop`.`delivery` ;

CREATE TABLE IF NOT EXISTS `db_shop`.`delivery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(500) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shop`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_shop`.`orders` ;

CREATE TABLE IF NOT EXISTS `db_shop`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datetime` TIMESTAMP(14) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(500) NOT NULL,
  `paymenttype` INT NOT NULL,
  `comment` VARCHAR(2000) NULL,
  `users_id` INT NOT NULL,
  `delivery_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_orders_users1_idx` (`users_id` ASC),
  INDEX `fk_orders_delivery1_idx` (`delivery_id` ASC),
  CONSTRAINT `fk_orders_users_id`
    FOREIGN KEY (`users_id`)
    REFERENCES `db_shop`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_delivery_id`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `db_shop`.`delivery` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shop`.`orders_has_goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_shop`.`orders_has_goods` ;

CREATE TABLE IF NOT EXISTS `db_shop`.`orders_has_goods` (
  `orders_id` INT NOT NULL,
  `goods_id` INT NOT NULL,
  `count` DOUBLE NOT NULL DEFAULT 1,
  PRIMARY KEY (`orders_id`, `goods_id`),
  INDEX `fk_orders_has_goods_goods1_idx` (`goods_id` ASC),
  INDEX `fk_orders_has_goods_orders1_idx` (`orders_id` ASC),
  CONSTRAINT `fk_orders_has_goods_orders_id`
    FOREIGN KEY (`orders_id`)
    REFERENCES `db_shop`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_has_goods_goods_id`
    FOREIGN KEY (`goods_id`)
    REFERENCES `db_shop`.`goods` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_shop`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_shop`.`images` ;

CREATE TABLE IF NOT EXISTS `db_shop`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(500) NULL,
  `alt` VARCHAR(500) NOT NULL,
  `path` VARCHAR(2048) NOT NULL,
  `goods_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `path_UNIQUE` (`path` ASC),
  INDEX `fk_images_goods1_idx` (`goods_id` ASC),
  CONSTRAINT `fk_images_goods_id`
    FOREIGN KEY (`goods_id`)
    REFERENCES `db_shop`.`goods` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_shop`.`categories`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_shop`;
INSERT INTO `db_shop`.`categories` (`id`, `parent`, `level`, `sort`, `title`, `description`, `url`, `flags`) VALUES (0, DEFAULT, 0, 0, 'Корень', NULL, '/', b'0000');

COMMIT;

